### ISSUE TITLE
v2.1 startup render needed canvas resize to display controls

### ISSUE THREAD

**Issue by quozl** [sugarlabs/music-blocks-embedded-activity#2]
After startup, an empty screen was seen, with or without the start block;

![github-before](https://user-images.githubusercontent.com/2936481/31913525-137c9b0e-b893-11e7-9463-69fbff58dab2.png)

Resizing the canvas showed control widgets;

![github-after](https://user-images.githubusercontent.com/2936481/31913536-1e2e66ae-b893-11e7-8170-1b238b4b5347.png)

On Ubuntu 16.04, Sugar 0.111, i386 VM.

**Comment by walterbender** [comment]
I am guessing it is some sort of race condition, as the resize code is called in the init function of the JS code. Also, I should remove the browser zoom buttons as Music Blocks wants the browser to be at 100% zoom.

**Comment by quozl** [comment]
Sorry, looks like it is specific to macOS Sierra and VirtualBox.  I've tested on Ubuntu 16.04 on NL3 hardware, and Ubuntu 16.04 inside VirtualBox on Ubuntu 16.04, and the problem does not occur.
